### ISSUE TITLE
The "Autobump" and "Alerts" and "key" buttons disappear as soon as I put my key in

### ISSUE THREAD

**Issue by GOTHMONEY** [yujincode/Flipd.gg-Autobumper#1]
When I put in my key and click OK the buttons and border just disappear and its like the extension just stops existing when I do that.
Going to chrome://extensions it gives me an "errors" button so maybe you should look into that.

**Comment by yujincode** [comment]
Should be fixed now. What key were you entering?

**Comment by GOTHMONEY** [comment]
> Should be fixed now. What key were you entering?

When going into inspect element, the "key" value didn't show up until the page refreshed which happened after i put mybbuser in there first and it giving me an error. After that the "key' value would pop up and I'd put it in.
After the update, it literally wont accept any "key" i put into it though.

**Comment by yujincode** [comment]
The key is not mybbuser. This is paid and the I issue the key. DM me if you are interested (yujin#4929).
